### ISSUE TITLE
VndError::fromJson() fails

### ISSUE THREAD

**Issue by kleijnweb** [ramsey/vnderror#4]
```
Missing argument 1 for Ramsey\VndError\VndError::__construct(), called in /home/jkleijn/Projects/php/kleijnweb/swagger-bundle/vendor/nocarrier/hal/src/Nocarrier/Hal.php on line 127 and defined

/home/jkleijn/Projects/php/kleijnweb/swagger-bundle/vendor/ramsey/vnderror/src/VndError.php:42
/home/jkleijn/Projects/php/kleijnweb/swagger-bundle/vendor/nocarrier/hal/src/Nocarrier/Hal.php:127
```

```
$ composer show --installed | grep -P '(hal|vnd)'
nocarrier/hal                     0.9.12  application/hal builder / formatter for PHP 5.3+
ramsey/vnderror                   3.0.0   application/vnd.error builder / formatter for PHP 5.3+
```

**Comment by ramsey** [comment]
It looks like commit https://github.com/blongden/hal/commit/065667be5e7619a10e29f5db35f78adcdcca51d9 is what introduced this bug, and it's been a problem for ramsey/vnderror since nocarrier/hal version 0.9.7. :-(

Specifically, it calls `new static()`, and since Ramsey\VndError inherits from Nocarrier\Hal, the code in the parent is trying to instantiate an object without passing the required constructor params required by the child. This is what I get for using inheritance across projects and why I should have used a decorator pattern or something else. :-)

The short-term solution is probably to do:

```
composer require nocarrier/hal=0.9.6
```

This will set it specifically to the tag before the changes that break my library. I might also consider setting this project's `composer.json` to use nocarrier/hal 0.9.6.

Longer term, I'll need to update the library to separate the dependencies so a change like this cannot break my library.

Sorry for the inconvenience!
